# Generated by Django 3.0.2 on 2020-01-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='rating',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
