# Generated by Django 3.0.2 on 2020-01-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0002_tv_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv',
            name='imdbid',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
