# Generated by Django 2.2.3 on 2019-07-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190719_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='photo',
            field=models.ImageField(max_length=1000, upload_to='photos'),
        ),
    ]
