# Generated by Django 2.2.3 on 2019-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190719_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='photo',
            field=models.ImageField(max_length=1000, upload_to='movie_photos'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='type',
            field=models.CharField(choices=[('action', 'Action'), ('horror', 'Horror'), ('adventure', 'Adventure'), ('scifi', 'Science Fiction'), ('romance', 'Romance'), ('drama', 'Drama'), ('thriller', 'Thriller')], max_length=10),
        ),
    ]
