# Generated by Django 2.2.3 on 2019-09-14 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20190913_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='photo',
            field=models.ImageField(max_length=1000, upload_to='tv_photos'),
        ),
    ]
