# Generated by Django 2.2.3 on 2019-09-14 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20190914_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='photo',
            field=models.ImageField(max_length=1000, upload_to='movie_photos'),
        ),
    ]
